pipenv run pyinstaller main.py `
    --noconfirm `
    --onefile `
    --name "YouTube-Scraper-windows" `
    --paths="src\" `
    --icon='main.ico' `
    --add-data "src\data\;src\data" `
    --hidden-import src `
    --exclude-module cv2 `
    --exclude-module numpy `
    --clean